const rrow=()=>`<div class="card rr" style="margin:6px 0"><div class="row"><input class="q1" list="tl" placeholder="উস্তাজের নাম"><input class="q2" placeholder="কোর্স নং"></div><div class="row"><input class="q3" placeholder="বিষয় (ঐচ্ছিক)"><input class="q4" placeholder="সময় লিখুন (ঠিক না থাকলে: পরে জানানো হবে)"></div><div class="row"><label class="meta">শুরু (ঐচ্ছিক)<input class="q5" type="time"></label><label class="meta">শেষ<input class="q6" type="time"></label></div></div>`;
const cC2=(r,tm,today)=>{const T=tm[r.teacher_id],nm=T?T.name:r.teacher_name;return `<div class="card bar"><div style="display:flex;gap:10px;align-items:center;flex:1">${nm?av({name:nm,photo:T&&T.photo}):''}<div style="flex:1"><span class="tag">${t('nth')[r.serial]||r.serial} ${t('serial')}</span> ${r.code?`<span class="tag">${esc(r.code)}</span>`:''} <b>${esc(r.subject)}</b>${nm?`<div>👨‍🏫 ${esc(nm)}</div>`:''}${r.room?`<div class="meta">🏠 ${esc(r.room)}</div>`:''}<div class="meta">⏰ ${r.start_time?TF(r.start_time)+(r.end_time?' – '+TF(r.end_time):''):(r.time?esc(r.time):t('tbd'))}</div>${cdEl(r,today)}</div></div><div>${isA()?`<button class="btn ghost" style="padding:2px 10px" onclick="editTime(${r.id})">⏰</button> `:''}${dB('routine',r.id)}</div></div>`};
X6.routine=async function(){const[{data:rs},{data:ts}]=await Promise.all([sb.from('routine').select('*'),sb.from('teachers').select('*').order('name')]);
 const d=(rs||[]).sort(byS),tm=Object.fromEntries((ts||[]).map(x=>[x.id,x]));
 let h=isA()?`<datalist id="tl">${(ts||[]).map(x=>`<option value="${esc(x.name)}">`).join('')}</datalist><div class="card"><b>➕ একদিনের সব ক্লাস একসাথে</b><div class="row" style="margin-top:6px"><select id="rd">${t('days').map((x,i)=>`<option value="${i}" ${i==RD?'selected':''}>${x}</option>`).join('')}</select><input id="rroom" placeholder="রুম নং (যেমন ২০৩/২০৪)"></div><div id="rrows">${rrow()}${rrow()}${rrow()}${rrow()}</div><button class="btn ghost" onclick="$('#rrows').insertAdjacentHTML('beforeend',rrow())">+ আরেকটা ক্লাস</button><textarea id="rhw" rows="2" placeholder="বাড়ির কাজ (ঐচ্ছিক)" style="width:100%;background:var(--bg);border:1px solid var(--line);border-radius:8px;padding:8px;color:inherit;font:inherit;margin-top:6px"></textarea><button class="btn" onclick="saveRR()">সব একসাথে সেভ করুন</button></div>`:'';
 const td=d.filter(x=>x.day==tIdx());
 h+=`<div class="day">📅 ${t('today')} (${t('days')[tIdx()]})</div>`+(td.length?td.map(r=>cC2(r,tm,1)).join(''):`<p class="meta">${t('noToday')}</p>`);
 t('days').forEach((n,i)=>{const it=d.filter(x=>x.day==i);if(it.length)h+=`<div class="day">${n} <span class="meta">(${N(it.length)}${t('cls')})</span></div>`+it.map(r=>cC2(r,tm,0)).join('')});return h};
async function saveRR(){const day=+$('#rd').value,room=$('#rroom').value.trim(),hw=$('#rhw').value.trim();const{data:ts}=await sb.from('teachers').select('id,name');
 const rows=[...document.querySelectorAll('#rrows .rr')].map((e,i)=>{const g=c=>e.querySelector('.'+c).value.trim(),n=g('q1'),T=(ts||[]).find(x=>x.name==n);return{day,serial:i+1,teacher_id:T?T.id:null,teacher_name:T?null:(n||null),code:g('q2'),subject:g('q3')||g('q2')||'—',time:g('q4'),start_time:g('q5')||null,end_time:g('q6')||null,room}}).filter(r=>r.code||r.teacher_name||r.subject!='—');
 if(!rows.length)return toast('কমপক্ষে একটা ক্লাস লিখুন');
 const{error}=await sb.from('routine').insert(rows);if(error)return toast(error.message);
 if(hw)await sb.from('notices').insert({title:'বাড়ির কাজ: '+hw,category:'homework'});
 await sb.from('notifications').insert({kind:'routine',text:t('nRoutine')+t('days')[day]+' · '+N(rows.length)+'টি ক্লাস'+(hw?' + বাড়ির কাজ':'')});RD=day;render()}
async function editTime(id){const v=prompt('সময় লিখুন (যেমন ৯:০০–১০:৩০ বা সকাল ১১টা)');if(v===null)return;await sb.from('routine').update({time:v.trim()}).eq('id',id);await sb.from('notifications').insert({kind:'routine',text:t('nRoutine')+v.trim()});render()}
const prow=()=>`<div class="card pr" style="margin:6px 0"><div class="row"><select class="w1">${Object.keys(PC).map(k=>`<option value="${k}">${PC[k][0]} ${PC[k][1]}</option>`).join('')}</select><input class="w2" placeholder="বিস্তারিত"></div><div class="row"><label class="meta">শুরু<input class="w3" type="time"></label><label class="meta">শেষ<input class="w4" type="time"></label></div></div>`;
const bulkP=()=>`<div class="card"><b>➕ একসাথে অনেক কাজ যোগ করুন</b><div id="prows">${prow()}${prow()}${prow()}</div><div class="row"><button class="btn ghost" onclick="$('#prows').insertAdjacentHTML('beforeend',prow())">+ আরেকটা</button><button class="btn" onclick="saveP2()">সব একসাথে সেভ</button></div></div>`;
const _pl=X6.plan;X6.plan=async function(){const h=await _pl();return h.replace('<div class="card"><div class="row"><select id="d1">',bulkP()+'<div class="card"><div class="row"><select id="d1">')};
async function saveP2(){const rows=[...document.querySelectorAll('#prows .pr')].map(e=>{const g=c=>e.querySelector('.'+c).value.trim();return{day:pd,cat:g('w1'),title:g('w2'),start_time:g('w3')||null,end_time:g('w4')||null}}).filter(r=>r.start_time);
 if(!rows.length)return toast('শুরুর সময় দিন');const{error}=await sb.from('daily').insert(rows);if(error)return toast(error.message);render()}
if(me)render();
