const sb=supabase.createClient('https://vfuuyeuglpziitjcwcou.supabase.co','sb_publishable_3q4eW3lP5gEEydTEZEZ1RQ_bix0JGwW');
const T={bn:{title:"আল ইতকান ৪০",uni:"আল কুরআন ও ইসলামিক স্টাডিজ, ইসলামী বিশ্ববিদ্যালয়",login:"লগইন",signup:"নতুন অ্যাকাউন্ট",allow:"নতুন হলে জিমেইল ও পাসওয়ার্ড দিয়ে 'নতুন অ্যাকাউন্ট' চাপুন",denied:"এই জিমেইল অনুমোদিত নয়। অ্যাডমিনের সাথে যোগাযোগ করুন।",notice:"নোটিশ",routine:"রুটিন",files:"ফাইল",chat:"চ্যাট",members:"সদস্য",add:"যোগ করুন",send:"পাঠান",search:"নাম, রোল বা রক্তের গ্রুপ দিয়ে খুঁজুন",msg:"মেসেজ লিখুন...",admin:"অ্যাডমিন",member:"সদস্য",ntitle:"নোটিশের শিরোনাম",time:"সময় লিখুন (যেমন ৯:০০–১০:৩০)",subj:"বিষয়",code:"কোর্স কোড",fname:"ফাইলের নাম (ঐচ্ছিক)",name:"নাম",roll:"রোল",blood:"রক্তের গ্রুপ",phone:"মোবাইল",fb:"ফেসবুক লিংক",addr:"ঠিকানা",save:"প্রোফাইল সেভ করুন",del:"মুছুন",none:"কিছু নেই",tbd:"সময় নির্ধারিত নয়",cls:"টি ক্লাস",mkA:"অ্যাডমিন বানান",mkM:"সদস্য করুন",teacher:"শিক্ষকের নাম",rmU:"রিমুভ",delMe:"আমার অ্যাকাউন্ট মুছুন",sure:"নিশ্চিত?",nNotice:"নতুন নোটিশ: ",nRoutine:"রুটিন আপডেট: ",nFile:"নতুন ফাইল: ",myp:"আমার প্রোফাইল",codeAsk:"ব্যাচের কোড দিন (হোয়াটসঅ্যাপ গ্রুপে পাবেন)",gname:"আপনার পূর্ণ নাম",groll:"রোল",submit:"জমা দিন",wrong:"কোড ভুল",waiting:"অ্যাডমিনের অনুমোদনের অপেক্ষায় আছেন। অনুমোদন হলে ঢুকতে পারবেন।",rejected:"আপনার অনুরোধ বাতিল হয়েছে। অ্যাডমিনের সাথে যোগাযোগ করুন।",again:"আবার দেখুন",out:"লগআউট",batchCode:"ব্যাচের গোপন কোড",pending:"অনুমোদনের অপেক্ষায়",st_new:"কোড দেয়নি",st_pending:"কোড দিয়েছে",st_rejected:"বাতিল",saved:"সেভ হয়েছে",grp:"ব্যাচের সকল সদস্যের গ্রুপ চ্যাট",days:["শনি","রবি","সোম","মঙ্গল","বুধ","বৃহস্পতি","শুক্র"]},
en:{title:"Al-Itqan 40",uni:"Al-Quran & Islamic Studies, Islamic University",login:"Log in",signup:"Create account",allow:"New here? Enter Gmail and password, then press Create account",denied:"This Gmail is not approved. Contact an admin.",notice:"Notices",routine:"Routine",files:"Files",chat:"Chat",members:"Members",add:"Add",send:"Send",search:"Search by name, roll or blood group",msg:"Type a message...",admin:"Admin",member:"Member",ntitle:"Notice title",time:"Type time (e.g. 9:00–10:30)",subj:"Subject",code:"Course code",fname:"File name (optional)",name:"Name",roll:"Roll",blood:"Blood group",phone:"Mobile",fb:"Facebook link",addr:"Address",save:"Save profile",del:"Delete",none:"Nothing here",tbd:"Time not fixed",cls:" classes",mkA:"Make admin",mkM:"Make member",teacher:"Teacher name",rmU:"Remove",delMe:"Delete my account",sure:"Are you sure?",nNotice:"New notice: ",nRoutine:"Routine updated: ",nFile:"New file: ",myp:"My profile",codeAsk:"Enter the batch code (from the WhatsApp group)",gname:"Your full name",groll:"Roll",submit:"Submit",wrong:"Wrong code",waiting:"Waiting for admin approval. You can enter once approved.",rejected:"Your request was rejected. Contact an admin.",again:"Check again",out:"Log out",batchCode:"Batch secret code",pending:"Waiting for approval",st_new:"No code yet",st_pending:"Code entered",st_rejected:"Rejected",saved:"Saved",grp:"Batch group chat",days:["Sat","Sun","Mon","Tue","Wed","Thu","Fri"]}};
let L=localStorage.L||'bn',tab='notice',me=null,RD=0,q='',ph=null,mem=[];
const t=k=>T[L][k],$=s=>document.querySelector(s),isA=()=>me&&me.role=='admin';
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const dt=d=>new Date(d).toLocaleDateString(L=='bn'?'bn-BD':'en-GB');
function toast(m){const e=$('#toast');e.textContent=m;e.style.display='block';setTimeout(()=>e.style.display='none',2500)}
async function signIn(){const{error}=await sb.auth.signInWithPassword({email:$('#em').value.trim(),password:$('#pw').value});error?$('#err').textContent=error.message:location.reload()}
async function signUp(){const{error}=await sb.auth.signUp({email:$('#em').value.trim(),password:$('#pw').value});error?$('#err').textContent=error.message:location.reload()}
function toggleLang(){L=L=='bn'?'en':'bn';localStorage.L=L;render()}
function go(x){tab=x;render()}
