async function render(){
 chrome();let h='';
 if(tab=='notice'){const{data}=await sb.from('notices').select('*').order('created_at',{ascending:false});
  h=(isA()?`<div class="card"><input id="a1" placeholder="${t('ntitle')}"><input id="a2" placeholder="${t('teacher')}"><button class="btn" onclick="a1.value&&add('notices',{title:a1.value,teacher:a2.value.trim()},t('nNotice')+a1.value)">${t('add')}</button></div>`:'')+(data||[]).map(n=>`<div class="card bar"><div><b>${esc(n.title)}</b>${n.teacher?`<div>👨‍🏫 ${esc(n.teacher)}</div>`:''}<div class="meta">${dt(n.created_at)}</div></div>${dB('notices',n.id)}</div>`).join('')}
 else if(tab=='routine'){const{data}=await sb.from('routine').select('*').order('id');const d=data||[];
  h=isA()?`<div class="card"><select id="r0" onchange="RD=+this.value">${t('days').map((x,i)=>`<option value="${i}" ${i==RD?'selected':''}>${x}</option>`).join('')}</select><div class="row"><input id="r3" placeholder="${t('code')}"><input id="r2" placeholder="${t('subj')}"></div><input id="r1" placeholder="${t('time')}"><button class="btn" onclick="RD=+r0.value;add('routine',{day:RD,code:r3.value,subject:r2.value,time:r1.value.trim()},t('nRoutine')+(r3.value||r2.value))">${t('add')}</button></div>`:'';
  t('days').forEach((n,i)=>{const it=d.filter(x=>x.day==i);if(it.length)h+=`<div class="day">${n} <span class="meta">(${it.length}${t('cls')})</span></div>`+it.map(r=>`<div class="card bar"><span><span class="tag">${esc(r.code||'—')}</span> <b>${esc(r.subject)}</b><div class="meta">${r.time?esc(r.time):t('tbd')}</div></span>${dB('routine',r.id)}</div>`).join('')})}
 else if(tab=='files'){const{data}=await sb.from('files').select('*').order('created_at',{ascending:false});
  h=(isA()?`<div class="card"><input id="f1" placeholder="${t('fname')}"><input id="ff" type="file" accept=".pdf,image/*"><button class="btn" onclick="up()">${t('add')}</button></div>`:'')+(data||[]).map(f=>`<div class="card bar"><a href="${esc(f.url)}" target="_blank" rel="noopener" style="color:var(--gold2)">📄 ${esc(f.name)}</a>${dB('files',f.id,f.path)}</div>`).join('')}
 else if(tab=='chat'){const{data}=await sb.from('messages').select('*').order('id',{ascending:false}).limit(100);
  h=`<div class="meta">👥 ${t('grp')}</div><div class="chat" id="ch">${(data||[]).reverse().map(msgH).join('')}</div><div class="row" style="margin-top:8px"><input id="cm" placeholder="${t('msg')}" onkeydown="if(event.key=='Enter')sendM()"><button class="btn" onclick="sendM()">${t('send')}</button></div>`;$('#view').innerHTML=h;const c=$('#ch');c.scrollTop=c.scrollHeight;return bell()}
 else if(tab=='notif'){const{data}=await sb.from('notifications').select('*').order('created_at',{ascending:false}).limit(50);localStorage.seen=new Date().toISOString();h=(data||[]).map(n=>`<div class="card">🔔 ${esc(n.text)}<div class="meta">${dt(n.created_at)}</div></div>`).join('')}
 else if(tab=='members'){const{data}=await sb.from('profiles').select('*').order('roll');mem=(data||[]).filter(m=>m.status=='approved');const pend=(data||[]).filter(m=>m.status!='approved');const{data:cs}=isA()?await sb.from('settings').select('value').eq('key','batch_code').single():{};
  h=`<div class="card"><b>${t('myp')}</b><div class="row" style="margin:6px 0">${av(me)}<input type="file" accept="image/*" onchange="pic(this)"></div>${['name','roll','blood','phone','fb','addr'].map(k=>`<input id="p_${k}" placeholder="${t(k)}" value="${esc(me[k])}">`).join('')}<button class="btn" onclick="saveP()">${t('save')}</button> <button class="btn ghost" onclick="delU('${me.id}',true)">${t('delMe')}</button></div>`
  +(isA()?`<div class="card"><b>${t('batchCode')}</b><div class="row"><input id="bcode" value="${esc(cs&&cs.value)}"><button class="btn" onclick="saveCode()">${t('save')}</button></div></div>`+(pend.length?`<div class="card"><b>${t('pending')} (${pend.length})</b>${pend.map(m=>`<div class="row" style="margin:6px 0"><span>${esc(m.name)} ${m.roll?'· '+esc(m.roll):''}<div class="meta">${esc(m.email)} · ${t('st_'+m.status)}</div></span><button class="btn" onclick="setS('${m.id}','approved')">✔</button><button class="btn ghost" onclick="setS('${m.id}','rejected')">✕</button></div>`).join('')}</div>`:''):'')
  +`<input id="sq" placeholder="🔍 ${t('search')}" oninput="q=this.value;$('#ml').innerHTML=list()"><div id="ml">${list()}</div>`}
 $('#view').innerHTML=h;bell()}
const list=()=>{const s=q.toLowerCase(),l=mem.filter(m=>[m.name,m.roll,m.blood].join(' ').toLowerCase().includes(s));return l.length?l.map(m=>`<div class="card mem">${av(m)}<div><b>${esc(m.name)}</b> ${m.roll?`<span class="tag">${t('roll')} ${esc(m.roll)}</span>`:''} ${m.blood?`<span class="tag">🩸 ${esc(m.blood)}</span>`:''}<div class="meta">${esc(m.phone||'')} ${m.addr?'· '+esc(m.addr):''} ${m.fb?`· <a style="color:var(--gold2)" target="_blank" rel="noopener" href="${esc(/^http/.test(m.fb)?m.fb:'https://'+m.fb)}">FB</a>`:''}</div>${isA()&&m.id!=me.id?`<button class="btn ghost" style="margin-top:4px;padding:2px 10px" onclick="setR('${m.id}','${m.role=='admin'?'member':'admin'}')">${t(m.role=='admin'?'mkM':'mkA')}</button> <button class="btn ghost" style="margin-top:4px;padding:2px 10px" onclick="delU('${m.id}',false)">${t('rmU')}</button>`:''}</div></div>`).join(''):`<p class="meta">${t('none')}</p>`};
const msgH=m=>`<div class="msg ${m.user_id==me.id?'me':''}" id="m${m.id}"><small>${esc(m.name)}${m.user_id==me.id||isA()?` <span style="cursor:pointer" onclick="delM(${m.id})">🗑</span>`:''}</small>${esc(m.body)}</div>`;
async function delM(id){if(!confirm(t('sure')))return;const{error}=await sb.from('messages').delete().eq('id',id);if(error)return toast(error.message);const e=$('#m'+id);e&&e.remove()}
async function delU(id,self){if(!confirm(t('sure')))return;const{error}=await sb.rpc('remove_user',{uid:id});if(error)return toast(error.message);if(self){await sb.auth.signOut();location.reload()}else render()}
function addMsg(m){const c=$('#ch');c.insertAdjacentHTML('beforeend',msgH(m));c.scrollTop=c.scrollHeight}
async function sendM(){const v=$('#cm').value.trim();if(!v)return;$('#cm').value='';const{error}=await sb.from('messages').insert({name:me.name,body:v});if(error)toast(error.message)}
async function up(){const f=$('#ff').files[0];if(!f)return;const nm=$('#f1').value||f.name,path=Date.now()+'.'+f.name.split('.').pop();
 const{error}=await sb.storage.from('files').upload(path,f);if(error)return toast(error.message);
 await add('files',{name:nm,url:sb.storage.from('files').getPublicUrl(path).data.publicUrl,path},t('nFile')+nm)}
function pic(i){const f=i.files[0];if(!f)return;const im=new Image();im.onload=()=>{const c=document.createElement('canvas');c.width=c.height=200;const s=Math.min(im.width,im.height);c.getContext('2d').drawImage(im,(im.width-s)/2,(im.height-s)/2,s,s,0,0,200,200);ph=c.toDataURL('image/jpeg',.7);toast('✔')};im.src=URL.createObjectURL(f)}
async function saveP(){const r={};['name','roll','blood','phone','fb','addr'].forEach(k=>r[k]=$('#p_'+k).value.trim());if(ph)r.photo=ph;
 const{error}=await sb.from('profiles').update(r).eq('id',me.id);if(error)return toast(error.message);Object.assign(me,r);toast(t('saved'));render()}
start();
