Object.assign(T.bn,{teachers:"উস্তাজ",tname:"উস্তাজের নাম",serial:"ক্লাস",pickT:"উস্তাজ বাছুন",pickC:"ক্লাস বাছুন (ঐচ্ছিক)",st:"শুরু",en:"শেষ",timeTxt:"অথবা সময় লিখুন (ঠিক না থাকলে)",today:"আজকের ক্লাস",noToday:"আজ কোনো ক্লাস নেই",startsIn:"শুরু হতে",runs:"চলছে · শেষ হতে",ended:"আজকের ক্লাস শেষ",left:"বাকি",d:"দিন",hr:"ঘণ্টা",mn:"মিনিট",clearAll:"সব মুছুন",nth:["","১ম","২য়","৩য়","৪র্থ","৫ম","৬ষ্ঠ"]});
Object.assign(T.en,{teachers:"Ustaz",tname:"Ustaz name",serial:"class",pickT:"Choose ustaz",pickC:"Choose class (optional)",st:"Start",en:"End",timeTxt:"Or type time (if not fixed)",today:"Today's classes",noToday:"No classes today",startsIn:"Starts in",runs:"Running · ends in",ended:"Today's class ended",left:"left",d:"d",hr:"h",mn:"m",clearAll:"Clear all",nth:["","1st","2nd","3rd","4th","5th","6th"]});
let tph=null;
const N=n=>L=='bn'?Number(n).toLocaleString('bn-BD'):n;
const TF=s=>{if(!s)return'';const[h,m]=s.split(':');return new Date(2000,0,1,+h,+m).toLocaleTimeString(L=='bn'?'bn-BD':'en-US',{hour:'numeric',minute:'2-digit'})};
const tIdx=()=>(new Date().getDay()+1)%7;
const byS=(a,b)=>(a.serial||0)-(b.serial||0)||String(a.start_time||'').localeCompare(b.start_time||'');
function dur(ms){let m=Math.max(0,Math.ceil(ms/60000)),d=Math.floor(m/1440);m-=d*1440;const h=Math.floor(m/60);m-=h*60;return[d?N(d)+' '+t('d'):'',h?N(h)+' '+t('hr'):'',(m||(!d&&!h))?N(m)+' '+t('mn'):''].filter(Boolean).join(' ')}
function cd(day,s,e,tm){if(!s)return'';const now=new Date(),[sh,sm]=s.split(':'),off=(day-tIdx()+7)%7;
 const mk=(o,x)=>{const[h,m]=x.split(':'),z=new Date(now);z.setDate(z.getDate()+o);z.setHours(+h,+m,0,0);return z};
 let st=mk(off,s),en=e?mk(off,e):new Date(st.getTime()+36e5);if(en<=st)en=new Date(st.getTime()+36e5);
 if(now>=st&&now<en)return t('runs')+' '+dur(en-now);
 if(now>=en){if(tm)return t('ended');st=mk(off+7,s)}
 return t('startsIn')+' '+dur(st-now)+' '+t('left')}
function tick(){document.querySelectorAll('.cd').forEach(x=>x.textContent=cd(+x.dataset.d,x.dataset.s,x.dataset.e,x.dataset.tm))}
setInterval(tick,20000);
function chrome(){document.documentElement.lang=L;$('#lang').textContent=L=='bn'?'EN':'বাংলা';document.querySelectorAll('[data-t]').forEach(e=>e.textContent=t(e.dataset.t));
 if(me){$('#role').textContent=isA()?t('admin'):t('member');$('#nav').innerHTML=['notice','routine','teachers','files','chat','members'].map(k=>`<button class="${tab==k?'on':''}" onclick="go('${k}')">${t(k)}</button>`).join('')}}
const cdEl=(r,tm)=>r.start_time?`<div class="cd" style="color:var(--gold2)" data-d="${r.day}" data-s="${r.start_time}" data-e="${r.end_time||''}" ${tm?'data-tm="1"':''}></div>`:'';
const cCard=(r,tm,today)=>{const tc=tm[r.teacher_id];return `<div class="card bar"><div style="display:flex;gap:10px;align-items:center;flex:1">${tc?av(tc):''}<div style="flex:1"><span class="tag">${t('nth')[r.serial]||r.serial} ${t('serial')}</span> <span class="tag">${esc(r.code||'—')}</span> <b>${esc(r.subject)}</b>${tc?`<div>${esc(tc.name)}</div>`:''}<div class="meta">${r.start_time?TF(r.start_time)+(r.end_time?' – '+TF(r.end_time):''):(r.time?esc(r.time):t('tbd'))}</div>${cdEl(r,today)}</div></div>${dB('routine',r.id)}</div>`};
const nCard=(n,tm,rm)=>{const r=rm[n.routine_id],tc=tm[n.teacher_id]||(r&&tm[r.teacher_id]);return `<div class="card bar"><div style="display:flex;gap:10px;align-items:center;flex:1">${tc?av(tc):''}<div style="flex:1"><b>${esc(n.title)}</b>${tc?`<div>👨‍🏫 ${esc(tc.name)}</div>`:(n.teacher?`<div>👨‍🏫 ${esc(n.teacher)}</div>`:'')}${r?`<div class="meta"><span class="tag">${esc(r.code||'')}</span> ${esc(r.subject)} · ${TF(r.start_time)||esc(r.time||'')}</div>${cdEl(r,0)}`:''}<div class="meta">${dt(n.created_at)}</div></div></div>${dB('notices',n.id)}</div>`};
const opts=(a,f)=>a.map(f).join('');
async function render(){
 chrome();let h='';
 if(tab=='notice'){const[{data:ns},{data:ts},{data:rs}]=await Promise.all([sb.from('notices').select('*').order('created_at',{ascending:false}),sb.from('teachers').select('*').order('name'),sb.from('routine').select('*')]);
  const tm=Object.fromEntries((ts||[]).map(x=>[x.id,x])),rm=Object.fromEntries((rs||[]).map(x=>[x.id,x]));
  h=(isA()?`<div class="card"><input id="a1" placeholder="${t('ntitle')}"><select id="a2"><option value="">${t('pickT')}</option>${opts(ts||[],x=>`<option value="${x.id}">${esc(x.name)}</option>`)}</select><select id="a3"><option value="">${t('pickC')}</option>${opts((rs||[]).sort(byS),r=>`<option value="${r.id}">${t('days')[r.day]} · ${t('nth')[r.serial]||''} · ${esc(r.code||'')} ${esc(r.subject)}</option>`)}</select><button class="btn" onclick="addN()">${t('add')}</button></div>`:'')+(ns||[]).map(n=>nCard(n,tm,rm)).join('')}
 else if(tab=='routine'){const[{data:rs},{data:ts}]=await Promise.all([sb.from('routine').select('*'),sb.from('teachers').select('*').order('name')]);
  const d=(rs||[]).sort(byS),tm=Object.fromEntries((ts||[]).map(x=>[x.id,x]));
  h=isA()?`<div class="card"><select id="r0" onchange="RD=+this.value">${t('days').map((x,i)=>`<option value="${i}" ${i==RD?'selected':''}>${x}</option>`).join('')}</select><div class="row"><select id="r5">${[1,2,3,4,5,6].map(i=>`<option value="${i}">${t('nth')[i]} ${t('serial')}</option>`).join('')}</select><select id="r4"><option value="">${t('pickT')}</option>${opts(ts||[],x=>`<option value="${x.id}">${esc(x.name)}</option>`)}</select></div><div class="row"><input id="r3" placeholder="${t('code')}"><input id="r2" placeholder="${t('subj')}"></div><div class="row"><label class="meta">${t('st')}<input id="r6" type="time"></label><label class="meta">${t('en')}<input id="r7" type="time"></label></div><input id="r1" placeholder="${t('timeTxt')}"><button class="btn" onclick="addR()">${t('add')}</button></div>`:'';
  const td=d.filter(x=>x.day==tIdx());
  h+=`<div class="day">📅 ${t('today')} (${t('days')[tIdx()]})</div>`+(td.length?td.map(r=>cCard(r,tm,1)).join(''):`<p class="meta">${t('noToday')}</p>`);
  t('days').forEach((n,i)=>{const it=d.filter(x=>x.day==i);if(it.length)h+=`<div class="day">${n} <span class="meta">(${N(it.length)}${t('cls')})</span></div>`+it.map(r=>cCard(r,tm,0)).join('')})}
 else if(tab=='teachers'){const{data}=await sb.from('teachers').select('*').order('name');
  h=(isA()?`<div class="card"><input id="tn" placeholder="${t('tname')}"><input type="file" accept="image/*" onchange="tpic(this)"><button class="btn" onclick="addT()">${t('add')}</button></div>`:'')+(data||[]).map(x=>`<div class="card bar"><div style="display:flex;gap:10px;align-items:center">${av(x)}<b>${esc(x.name)}</b></div>${dB('teachers',x.id)}</div>`).join('')}
 else if(tab=='files'){const{data}=await sb.from('files').select('*').order('created_at',{ascending:false});
  h=(isA()?`<div class="card"><input id="f1" placeholder="${t('fname')}"><input id="ff" type="file" accept=".pdf,image/*"><button class="btn" onclick="up()">${t('add')}</button></div>`:'')+(data||[]).map(f=>`<div class="card bar"><a href="${esc(f.url)}" target="_blank" rel="noopener" style="color:var(--gold2)">📄 ${esc(f.name)}</a>${dB('files',f.id,f.path)}</div>`).join('')}
 else if(tab=='chat'){const{data}=await sb.from('messages').select('*').order('id',{ascending:false}).limit(100);
  h=`<div class="meta">👥 ${t('grp')}</div><div class="chat" id="ch">${(data||[]).reverse().map(msgH).join('')}</div><div class="row" style="margin-top:8px"><input id="cm" placeholder="${t('msg')}" onkeydown="if(event.key=='Enter')sendM()"><button class="btn" onclick="sendM()">${t('send')}</button></div>`;$('#view').innerHTML=h;const c=$('#ch');c.scrollTop=c.scrollHeight;return bell()}
 else if(tab=='notif'){const{data}=await sb.from('notifications').select('*').order('created_at',{ascending:false}).limit(50);localStorage.seen=new Date().toISOString();const a=data||[];
  h=(isA()&&a.length?`<button class="btn ghost" style="margin-bottom:10px" onclick="clrN()">${t('clearAll')}</button>`:'')+a.map(n=>`<div class="card bar"><div>🔔 ${esc(n.text)}<div class="meta">${dt(n.created_at)}</div></div>${dB('notifications',n.id)}</div>`).join('')}
 else if(tab=='members'){const{data}=await sb.from('profiles').select('*').order('roll');mem=(data||[]).filter(m=>m.status=='approved');const pend=(data||[]).filter(m=>m.status!='approved');const{data:cs}=isA()?await sb.from('settings').select('value').eq('key','batch_code').single():{};
  h=`<div class="card"><b>${t('myp')}</b><div class="row" style="margin:6px 0">${av(me)}<input type="file" accept="image/*" onchange="pic(this)"></div>${['name','roll','blood','phone','fb','addr'].map(k=>`<input id="p_${k}" placeholder="${t(k)}" value="${esc(me[k])}">`).join('')}<button class="btn" onclick="saveP()">${t('save')}</button> <button class="btn ghost" onclick="delU('${me.id}',true)">${t('delMe')}</button></div>`
  +(isA()?`<div class="card"><b>${t('batchCode')}</b><div class="row"><input id="bcode" value="${esc(cs&&cs.value)}"><button class="btn" onclick="saveCode()">${t('save')}</button></div></div>`+(pend.length?`<div class="card"><b>${t('pending')} (${pend.length})</b>${pend.map(m=>`<div class="row" style="margin:6px 0"><span>${esc(m.name)} ${m.roll?'· '+esc(m.roll):''}<div class="meta">${esc(m.email)} · ${t('st_'+m.status)}</div></span><button class="btn" onclick="setS('${m.id}','approved')">✔</button><button class="btn ghost" onclick="setS('${m.id}','rejected')">✕</button></div>`).join('')}</div>`:''):'')
  +`<input id="sq" placeholder="🔍 ${t('search')}" oninput="q=this.value;$('#ml').innerHTML=list()"><div id="ml">${list()}</div>`}
 $('#view').innerHTML=h;bell();tick()}
function addN(){const v=$('#a1').value.trim();if(!v)return;add('notices',{title:v,teacher_id:$('#a2').value?+$('#a2').value:null,routine_id:$('#a3').value?+$('#a3').value:null},t('nNotice')+v)}
function addR(){RD=+$('#r0').value;const v=i=>$('#r'+i).value;add('routine',{day:RD,serial:+v(5),teacher_id:v(4)?+v(4):null,code:v(3),subject:v(2),start_time:v(6)||null,end_time:v(7)||null,time:v(1).trim()},t('nRoutine')+(v(3)||v(2)))}
async function addT(){const n=$('#tn').value.trim();if(!n)return;const{error}=await sb.from('teachers').insert({name:n,photo:tph});if(error)return toast(error.message);tph=null;render()}
async function clrN(){if(!confirm(t('sure')))return;await sb.from('notifications').delete().gt('id',0);render()}
const list=()=>{const s=q.toLowerCase(),l=mem.filter(m=>[m.name,m.roll,m.blood].join(' ').toLowerCase().includes(s));return l.length?l.map(m=>`<div class="card mem">${av(m)}<div><b>${esc(m.name)}</b> ${m.roll?`<span class="tag">${t('roll')} ${esc(m.roll)}</span>`:''} ${m.blood?`<span class="tag">🩸 ${esc(m.blood)}</span>`:''}<div class="meta">${esc(m.phone||'')} ${m.addr?'· '+esc(m.addr):''} ${m.fb?`· <a style="color:var(--gold2)" target="_blank" rel="noopener" href="${esc(/^http/.test(m.fb)?m.fb:'https://'+m.fb)}">FB</a>`:''}</div>${isA()&&m.id!=me.id?`<button class="btn ghost" style="margin-top:4px;padding:2px 10px" onclick="setR('${m.id}','${m.role=='admin'?'member':'admin'}')">${t(m.role=='admin'?'mkM':'mkA')}</button> <button class="btn ghost" style="margin-top:4px;padding:2px 10px" onclick="delU('${m.id}',false)">${t('rmU')}</button>`:''}</div></div>`).join(''):`<p class="meta">${t('none')}</p>`};
const msgH=m=>`<div class="msg ${m.user_id==me.id?'me':''}" id="m${m.id}"><small>${esc(m.name)}${m.user_id==me.id||isA()?` <span style="cursor:pointer" onclick="delM(${m.id})">🗑</span>`:''}</small>${esc(m.body)}</div>`;
async function delM(id){if(!confirm(t('sure')))return;const{error}=await sb.from('messages').delete().eq('id',id);if(error)return toast(error.message);const e=$('#m'+id);e&&e.remove()}
async function delU(id,self){if(!confirm(t('sure')))return;const{error}=await sb.rpc('remove_user',{uid:id});if(error)return toast(error.message);if(self){await sb.auth.signOut();location.reload()}else render()}
function addMsg(m){const c=$('#ch');c.insertAdjacentHTML('beforeend',msgH(m));c.scrollTop=c.scrollHeight}
async function sendM(){const v=$('#cm').value.trim();if(!v)return;$('#cm').value='';const{error}=await sb.from('messages').insert({name:me.name,body:v});if(error)toast(error.message)}
async function up(){const f=$('#ff').files[0];if(!f)return;const nm=$('#f1').value||f.name,path=Date.now()+'.'+f.name.split('.').pop();
 const{error}=await sb.storage.from('files').upload(path,f);if(error)return toast(error.message);
 await add('files',{name:nm,url:sb.storage.from('files').getPublicUrl(path).data.publicUrl,path},t('nFile')+nm)}
function rz(f,cb){const im=new Image();im.onload=()=>{const c=document.createElement('canvas');c.width=c.height=200;const s=Math.min(im.width,im.height);c.getContext('2d').drawImage(im,(im.width-s)/2,(im.height-s)/2,s,s,0,0,200,200);cb(c.toDataURL('image/jpeg',.7))};im.src=URL.createObjectURL(f)}
function pic(i){i.files[0]&&rz(i.files[0],d=>{ph=d;toast('✔')})}
function tpic(i){i.files[0]&&rz(i.files[0],d=>{tph=d;toast('✔')})}
async function saveP(){const r={};['name','roll','blood','phone','fb','addr'].forEach(k=>r[k]=$('#p_'+k).value.trim());if(ph)r.photo=ph;
 const{error}=await sb.from('profiles').update(r).eq('id',me.id);if(error)return toast(error.message);Object.assign(me,r);toast(t('saved'));render()}
start();
