Object.assign(T.bn,{blood:"রক্তদাতা",comp:"অভিযোগ",bAll:"সব",call:"কল",cTitle:"বিষয়",cBody:"বিস্তারিত লিখুন",anon:"নাম গোপন রাখুন",cSend:"জমা দিন",reply:"উত্তর লিখুন",replyB:"উত্তর সেভ",lkT:"লিংকের নাম",lkU:"লিংক (YouTube/Drive ইত্যাদি)",lkAdd:"লিংক যোগ করুন",noB:"এই গ্রুপে কেউ নেই",cCat:"ধরন",trk:"ট্র্যাকিং কোড দিয়ে দেখুন",trkB:"দেখুন",trkNo:"এই কোডে কিছু পাওয়া যায়নি",yourCode:"আপনার ট্র্যাকিং কোড (লিখে রাখুন): ",myC:"আপনার অভিযোগ",allC:"সব অভিযোগ",noC:"কোনো অভিযোগ নেই"});
Object.assign(T.en,{blood:"Blood donors",comp:"Complaints",bAll:"All",call:"Call",cTitle:"Subject",cBody:"Write details",anon:"Keep my name hidden",cSend:"Submit",reply:"Write reply",replyB:"Save reply",lkT:"Link name",lkU:"Link (YouTube/Drive etc.)",lkAdd:"Add link",noB:"No one in this group",cCat:"Type",trk:"Track with code",trkB:"Check",trkNo:"Nothing found for this code",yourCode:"Your tracking code (write it down): ",myC:"Your complaints",allC:"All complaints",noC:"No complaints"});
const XT=['blood','comp'];let bg='',cf='',cc='';
const CAT={academic:'একাডেমিক',room:'রুম/সুবিধা',exam:'পরীক্ষা',other:'অন্যান্য'},ST={pending:'অপেক্ষায়',review:'পর্যালোচনায়',done:'সমাধান'},SC={pending:'#7a5a1a',review:'#1a4a7a',done:'#1a6a3a'};
const stTag=s=>`<span class="tag" style="background:${SC[s]||SC.pending}">${ST[s]||ST.pending}</span>`;
const _chrome=chrome;
chrome=function(){_chrome();if(me)$('#nav').insertAdjacentHTML('beforeend',XT.map(k=>`<button class="${tab==k?'on':''}" onclick="go('${k}')">${t(k)}</button>`).join(''))};
const lkForm=()=>`<div class="card"><input id="lk1" placeholder="${t('lkT')}"><input id="lk2" placeholder="${t('lkU')}"><button class="btn" onclick="addLk()">${t('lkAdd')}</button></div>`;
function addLk(){const n=$('#lk1').value.trim(),u=$('#lk2').value.trim();if(!n||!/^https?:\/\//.test(u))return toast('https://...');add('files',{name:n,url:u},t('nFile')+n)}
async function rBlood(){const{data}=await sb.from('profiles').select('name,roll,blood,phone,addr,photo').eq('status','approved').neq('blood','');
 const G=['A+','A-','B+','B-','O+','O-','AB+','AB-'],l=(data||[]).filter(m=>m.blood&&(!bg||m.blood.trim().toUpperCase()==bg));
 return `<div class="row" style="flex-wrap:wrap">${['',...G].map(g=>`<button class="btn ${g==bg?'':'ghost'}" style="padding:2px 12px;flex:none" onclick="bg='${g}';render()">${g||t('bAll')}</button>`).join('')}</div><div style="height:10px"></div>`+(l.length?l.map(m=>`<div class="card bar"><div style="display:flex;gap:10px;align-items:center">${av(m)}<div><b>${esc(m.name)}</b> <span class="tag">🩸 ${esc(m.blood)}</span><div class="meta">${esc(m.addr||'')} ${m.roll?'· '+t('roll')+' '+esc(m.roll):''}</div></div></div>${m.phone?`<a class="btn" href="tel:${esc(m.phone)}" style="text-decoration:none">${t('call')}</a>`:''}</div>`).join(''):`<p class="meta">${t('noB')}</p>`)}
const opt=(o,sel)=>Object.keys(o).map(k=>`<option value="${k}" ${k==sel?'selected':''}>${o[k]}</option>`).join('');
async function rComp(){const{data}=await sb.from('complaints').select('*').order('created_at',{ascending:false});const a=data||[],l=a.filter(c=>(!cf||c.status==cf)&&(!cc||c.category==cc));
 const fm=`<div class="card"><select id="c0">${opt(CAT,'other')}</select><input id="c1" placeholder="${t('cTitle')}"><textarea id="c2" rows="3" placeholder="${t('cBody')}" style="width:100%;background:var(--bg);border:1px solid var(--line);border-radius:8px;padding:8px;color:inherit;font:inherit"></textarea><label class="meta"><input id="c3" type="checkbox" style="width:auto"> ${t('anon')}</label><br><button class="btn" onclick="sendC()">${t('cSend')}</button></div>`;
 const tk=`<div class="card"><div class="row"><input id="tk" placeholder="${t('trk')}"><button class="btn" onclick="trackC()">${t('trkB')}</button></div><div id="tkr"></div></div>`;
 const sm=isA()?`<div class="row" style="margin-bottom:8px">${Object.keys(ST).map(k=>`<div class="card" style="text-align:center;margin:0;cursor:pointer" onclick="cf=cf=='${k}'?'':'${k}';render()">${stTag(k)}<div style="font-size:22px;font-weight:700">${a.filter(c=>c.status==k).length}</div></div>`).join('')}</div><select onchange="cc=this.value;render()"><option value="">${t('allC')} · ${t('cCat')}</option>${opt(CAT,cc)}</select>`:'';
 return fm+tk+sm+`<div class="day">${isA()?t('allC'):t('myC')} (${l.length})</div>`+(l.length?l.map(c=>`<div class="card"><div class="bar"><b>${esc(c.title)}</b>${stTag(c.status)}</div><span class="tag">${CAT[c.category]||CAT.other}</span><div style="margin-top:4px">${esc(c.body)}</div><div class="meta">${c.name?esc(c.name):'🕶 '+(isA()?'নাম গোপন':'')} · ${dt(c.created_at)}</div>${c.reply?`<div style="color:var(--gold2)">↳ ${esc(c.reply)}</div>`:''}${isA()?`<div class="row" style="flex-wrap:wrap;margin-top:6px">${Object.keys(ST).map(k=>`<button class="btn ${c.status==k?'':'ghost'}" style="padding:1px 10px;flex:none" onclick="setCS(${c.id},'${k}')">${ST[k]}</button>`).join('')}</div><input id="rp${c.id}" placeholder="${t('reply')}" value="${esc(c.reply||'')}"><button class="btn" onclick="repC(${c.id})">${t('replyB')}</button> ${dB('complaints',c.id)}`:''}</div>`).join(''):`<p class="meta">${t('noC')}</p>`)}
async function sendC(){const ti=$('#c1').value.trim();if(!ti)return;const an=$('#c3').checked,code=an?Math.random().toString(36).slice(2,8).toUpperCase():null;
 const{error}=await sb.from('complaints').insert({title:ti,body:$('#c2').value.trim(),category:$('#c0').value,code,user_id:an?null:me.id,name:an?null:me.name});
 if(error)return toast(error.message);if(an)alert(t('yourCode')+code);toast(t('saved'));render()}
async function trackC(){const{data}=await sb.rpc('track_complaint',{c:$('#tk').value});$('#tkr').innerHTML=data?`<div style="margin-top:6px"><b>${esc(data.title)}</b> ${stTag(data.status)}${data.reply?`<div style="color:var(--gold2)">↳ ${esc(data.reply)}</div>`:''}</div>`:`<div class="meta">${t('trkNo')}</div>`}
async function setCS(id,s){await sb.from('complaints').update({status:s}).eq('id',id);render()}
async function repC(id){const r=$('#rp'+id).value.trim(),u={reply:r};const{data:c}=await sb.from('complaints').select('status').eq('id',id).single();if(r&&c&&c.status=='pending')u.status='review';await sb.from('complaints').update(u).eq('id',id);render()}
const _render=render;
render=async function(){
 if(!XT.includes(tab)){await _render();if(tab=='files'&&isA())$('#view').insertAdjacentHTML('afterbegin',lkForm());return}
 chrome();$('#view').innerHTML=tab=='blood'?await rBlood():await rComp();bell()};
if(me)render();
