const NC={general:['সাধারণ','#4a4a4a'],urgent:['🚨 জরুরি','#8a1020'],assignment:['📝 অ্যাসাইনমেন্ট','#1a4a7a'],tutorial:['📘 টিউটোরিয়াল','#5a3a8a'],homework:['🏠 বাড়ির কাজ','#7a5a1a'],exam:['🧪 পরীক্ষা','#7a2a1a'],sports:['⚽ খেলাধুলা','#1a6a3a']};
const ctag=k=>{const c=NC[k]||NC.general;return `<span class="tag" style="background:${c[1]}">${c[0]}</span>`};
const dueFmt=d=>new Date(d).toLocaleString(L=='bn'?'bn-BD':'en-GB',{day:'numeric',month:'short',hour:'numeric',minute:'2-digit'});
const duEl=d=>`<div class="du" style="color:var(--gold2);font-weight:700" data-due="${d}"></div>`;
let nf='';
X6.notice=async function(){const[{data:ns},{data:ts},{data:rs}]=await Promise.all([sb.from('notices').select('*').order('created_at',{ascending:false}),sb.from('teachers').select('*').order('name'),sb.from('routine').select('*')]);
 const tm=Object.fromEntries((ts||[]).map(x=>[x.id,x])),rm=Object.fromEntries((rs||[]).map(x=>[x.id,x])),l=(ns||[]).filter(n=>!nf||(n.category||'general')==nf);
 const form=isA()?`<div class="card"><input id="a1" placeholder="${t('ntitle')}"><select id="a4">${Object.keys(NC).map(k=>`<option value="${k}">${NC[k][0]}</option>`).join('')}</select><label class="meta">সময় / জমার শেষ সময় (ঐচ্ছিক)<input id="a5" type="datetime-local"></label><select id="a2"><option value="">${t('pickT')}</option>${(ts||[]).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select><select id="a3"><option value="">${t('pickC')}</option>${(rs||[]).sort(byS).map(r=>`<option value="${r.id}">${t('days')[r.day]} · ${t('nth')[r.serial]||''} · ${esc(r.code||'')} ${esc(r.subject)}</option>`).join('')}</select><button class="btn" onclick="addN2()">${t('add')}</button></div>`:'';
 const chips=`<div class="row" style="flex-wrap:wrap;margin-bottom:8px">${['',...Object.keys(NC)].map(k=>`<button class="btn ${k==nf?'':'ghost'}" style="padding:1px 10px;flex:none" onclick="nf='${k}';render()">${k?NC[k][0]:t('bAll')}</button>`).join('')}</div>`;
 return form+chips+l.map(n=>{const r=rm[n.routine_id],T=tm[n.teacher_id]||(r&&tm[r.teacher_id]);return `<div class="card bar"><div style="display:flex;gap:10px;align-items:center;flex:1">${T?av(T):''}<div style="flex:1">${ctag(n.category||'general')} <b>${esc(n.title)}</b>${T?`<div>👨‍🏫 ${esc(T.name)}</div>`:(n.teacher?`<div>👨‍🏫 ${esc(n.teacher)}</div>`:'')}${r?`<div class="meta"><span class="tag">${esc(r.code||'')}</span> ${esc(r.subject)} · ${TF(r.start_time)||esc(r.time||'')}</div>${cdEl(r,0)}`:''}${n.due?`<div class="meta">📅 ${dueFmt(n.due)}</div>${duEl(n.due)}`:''}<div class="meta">${dt(n.created_at)}</div></div></div>${dB('notices',n.id)}</div>`}).join('')};
function addN2(){const v=$('#a1').value.trim();if(!v)return;const c=$('#a4').value,d=$('#a5').value;add('notices',{title:v,category:c,due:d?new Date(d).toISOString():null,teacher_id:$('#a2').value?+$('#a2').value:null,routine_id:$('#a3').value?+$('#a3').value:null},NC[c][0]+': '+v)}
X6.plan=async function(){const[{data:pl},{data:ns}]=await Promise.all([sb.from('plans').select('*').order('done').order('due',{nullsFirst:false}),sb.from('notices').select('*').in('category',['assignment','tutorial','homework','exam']).gt('due',new Date().toISOString()).order('due').limit(10)]);
 const a=pl||[],dn=a.filter(x=>x.done).length,pc=a.length?Math.round(dn/a.length*100):0;
 return `<div class="day">📌 ব্যাচের আসন্ন ডেডলাইন</div>`+((ns||[]).length?ns.map(n=>`<div class="card">${ctag(n.category)} <b>${esc(n.title)}</b><div class="meta">📅 ${dueFmt(n.due)}</div>${duEl(n.due)}</div>`).join(''):'<p class="meta">কোনো আসন্ন ডেডলাইন নেই</p>')
 +`<div class="day">🎯 আমার পড়ার লক্ষ্য</div><div class="card"><input id="pl1" placeholder="যেমন: তাফসীর ৫ পৃষ্ঠা পড়া"><label class="meta">শেষ সময় (ঐচ্ছিক)<input id="pl2" type="datetime-local"></label><button class="btn" onclick="addP()">${t('add')}</button></div>`
 +(a.length?`<div class="card"><div class="meta">সম্পন্ন ${bn(dn)}/${bn(a.length)} · ${bn(pc)}%</div><div style="background:var(--bg);border-radius:6px;height:10px"><div style="width:${pc}%;background:var(--gold);height:10px;border-radius:6px"></div></div></div>`:'')
 +a.map(x=>`<div class="card bar"><label style="flex:1;${x.done?'text-decoration:line-through;opacity:.6':''}"><input type="checkbox" style="width:auto" ${x.done?'checked':''} onchange="togP(${x.id},this.checked)"> ${esc(x.title)}${x.due?`<div class="meta">📅 ${dueFmt(x.due)}</div>${x.done?'':duEl(x.due)}`:''}</label><button class="btn ghost" onclick="delP(${x.id})">${t('del')}</button></div>`).join('')};
async function addP(){const v=$('#pl1').value.trim();if(!v)return;const d=$('#pl2').value;await sb.from('plans').insert({title:v,due:d?new Date(d).toISOString():null});render()}
async function togP(id,c){await sb.from('plans').update({done:c}).eq('id',id);render()}
async function delP(id){await sb.from('plans').delete().eq('id',id);render()}
X6.profile=async function(){return `<div class="card"><b>${t('myp')}</b><div class="row" style="margin:6px 0">${av(me)}<input type="file" accept="image/*" onchange="pic(this)"></div>${['name','roll','blood','phone','fb','addr'].map(k=>`<input id="p_${k}" placeholder="${t(k)}" value="${esc(me[k])}">`).join('')}<button class="btn" onclick="saveP()">${t('save')}</button> <button class="btn ghost" onclick="delU('${me.id}',true)">${t('delMe')}</button></div>`};
const list2=()=>{const s=q.toLowerCase(),l=mem.filter(m=>[m.name,m.roll,m.blood].join(' ').toLowerCase().includes(s));return l.length?l.map(m=>`<div class="card mem">${av(m)}<div style="flex:1"><b>${esc(m.name)}</b> ${m.roll?`<span class="tag">${t('roll')} ${esc(m.roll)}</span>`:''} ${m.blood?`<span class="tag">🩸 ${esc(m.blood)}</span>`:''}<div class="meta">${esc(m.phone||'')} ${m.addr?'· '+esc(m.addr):''} ${m.fb?`· <a style="color:var(--gold2)" target="_blank" rel="noopener" href="${esc(/^http/.test(m.fb)?m.fb:'https://'+m.fb)}">FB</a>`:''}</div><div class="row" style="flex-wrap:wrap;margin-top:4px">${m.phone?`<a class="btn" style="text-decoration:none;padding:2px 12px;flex:none" href="tel:${esc(m.phone)}">📞 ${t('call')}</a>`:''}${m.id!=me.id?`<button class="btn ghost" style="padding:2px 12px;flex:none" onclick="openDm('${m.id}')">💬 চ্যাট</button>`:''}${isA()&&m.id!=me.id?`<button class="btn ghost" style="padding:2px 10px;flex:none" onclick="setR('${m.id}','${m.role=='admin'?'member':'admin'}')">${t(m.role=='admin'?'mkM':'mkA')}</button><button class="btn ghost" style="padding:2px 10px;flex:none" onclick="delU('${m.id}',false)">${t('rmU')}</button>`:''}</div></div></div>`).join(''):`<p class="meta">${t('none')}</p>`};
function siteImg(i,key,w){const f=i.files[0];if(!f)return;const im=new Image();im.onload=async()=>{const c=document.createElement('canvas');if(key=='logo'){c.width=c.height=w;const s=Math.min(im.width,im.height);c.getContext('2d').drawImage(im,(im.width-s)/2,(im.height-s)/2,s,s,0,0,w,w)}else{c.width=w;c.height=Math.round(im.height*w/im.width);c.getContext('2d').drawImage(im,0,0,c.width,c.height)}const{error}=await sb.from('site').upsert({key,value:c.toDataURL('image/jpeg',.7)});if(error)return toast(error.message);toast(t('saved'));loadSite()};im.src=URL.createObjectURL(f)}
X6.members=async function(){const{data}=await sb.from('profiles').select('*').order('roll');mem=(data||[]).filter(m=>m.status=='approved');const pend=(data||[]).filter(m=>m.status!='approved');const{data:cs}=isA()?await sb.from('settings').select('value').eq('key','batch_code').single():{};
 const ad=isA()?`<div class="card"><b>${t('batchCode')}</b><div class="row"><input id="bcode" value="${esc(cs&&cs.value)}"><button class="btn" onclick="saveCode()">${t('save')}</button></div></div><div class="card"><b>🖼 লোগো ও কভার ছবি বদলান</b><div class="meta">লোগো</div><input type="file" accept="image/*" onchange="siteImg(this,'logo',200)"><div class="meta">কভার ছবি</div><input type="file" accept="image/*" onchange="siteImg(this,'cover',800)"></div>`+(pend.length?`<div class="card"><b>${t('pending')} (${pend.length})</b>${pend.map(m=>`<div class="row" style="margin:6px 0"><span>${esc(m.name)} ${m.roll?'· '+esc(m.roll):''}<div class="meta">${esc(m.email)} · ${t('st_'+m.status)}</div></span><button class="btn" onclick="setS('${m.id}','approved')">✔</button><button class="btn ghost" onclick="setS('${m.id}','rejected')">✕</button></div>`).join('')}</div>`:''):'';
 return ad+`<input id="sq" placeholder="🔍 ${t('search')}" value="${esc(q)}" oninput="q=this.value;$('#ml').innerHTML=list2()"><div id="ml">${list2()}</div>`};
function openDm(id){dmWith=id;tab='dm';render()}
const nm=id=>(mem.find(m=>m.id==id)||{}).name||'?';
const dmH=m=>`<div class="msg ${m.sender==me.id?'me':''}" id="d${m.id}">${esc(m.body)}${m.sender==me.id?` <span style="cursor:pointer" onclick="delDm(${m.id})">🗑</span>`:''}</div>`;
function addDm(m){const c=$('#dch');if(!c||$('#d'+m.id))return;c.insertAdjacentHTML('beforeend',dmH(m));c.scrollTop=c.scrollHeight}
async function sendDm(){const v=$('#dmi').value.trim();if(!v)return;$('#dmi').value='';const{error}=await sb.from('dms').insert({receiver:dmWith,body:v});if(error)toast(error.message)}
async function delDm(id){if(!confirm(t('sure')))return;await sb.from('dms').delete().eq('id',id);const e=$('#d'+id);if(e)e.remove()}
X6.dm=async function(){
 if(!mem.length){const{data}=await sb.from('profiles').select('*').eq('status','approved').order('roll');mem=data||[]}
 if(!dmWith){const{data}=await sb.from('dms').select('sender,receiver,body,created_at').order('id',{ascending:false}).limit(300);const seen={},cv=[];(data||[]).forEach(m=>{const o=m.sender==me.id?m.receiver:m.sender;if(!seen[o]){seen[o]=1;cv.push([o,m])}});
  return `<div class="card"><select onchange="this.value&&openDm(this.value)"><option value="">➕ নতুন চ্যাট শুরু করুন</option>${mem.filter(m=>m.id!=me.id).map(m=>`<option value="${m.id}">${esc(m.name)}</option>`).join('')}</select></div>`+(cv.length?cv.map(([o,m])=>`<div class="card bar" style="cursor:pointer" onclick="openDm('${o}')"><div><b>${esc(nm(o))}</b><div class="meta">${m.sender==me.id?'আপনি: ':''}${esc(m.body).slice(0,40)}</div></div><span class="meta">${dt(m.created_at)}</span></div>`).join(''):'<p class="meta">এখনো কোনো ব্যক্তিগত চ্যাট নেই</p>')}
 const p=mem.find(m=>m.id==dmWith)||{name:'?'};const{data}=await sb.from('dms').select('*').or(`and(sender.eq.${me.id},receiver.eq.${dmWith}),and(sender.eq.${dmWith},receiver.eq.${me.id})`).order('id',{ascending:false}).limit(100);
 return `<div class="bar" style="margin-bottom:6px"><button class="btn ghost" onclick="dmWith=null;render()">←</button><b>${esc(p.name)}</b>${p.phone?`<a class="btn" style="text-decoration:none" href="tel:${esc(p.phone)}">📞</a>`:'<span></span>'}</div><div class="chat" id="dch">${(data||[]).reverse().map(dmH).join('')}</div>${emoBar('dmi')}<div class="row" style="margin-top:8px"><button class="btn ghost" style="flex:none;padding:6px 10px" onclick="tE()">😊</button><input id="dmi" placeholder="${t('msg')}" onkeydown="if(event.key=='Enter')sendDm()"><button class="btn" onclick="sendDm()">${t('send')}</button></div>`};
if(me)render();
